# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#what branch we are watching
trigger:
  - 'master'

pool: 
  vmImage: 'ubuntu-latest'

variables:
- name: 'Student' 
  value: 'Sulav'
#watch for PR's
pr: 'none'

#groups sequential actions
stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - script: dotnet build 'pipeLineMvcDemo/pipeLineMvcDemo.csproj'
          - script: echo "Hey there $(Student)!"

      - job: 'test'
        dependsOn: 'build'
        steps:
          - script: 'dotnet test'

      - job: 'publish'
        dependsOn: 'test'
        steps:
          - script: 'dotnet publish'

name: '$(date:yyyyMMdd)$(rev:rr)'

        